Adds all classes for Hits
aymeric-giraudet/svelte-algolia-instantsearch pull request #9
Opened 2023-03-12 17:08 UTC by jonasNobile

Enable to add classes to all Hits elements.

2023-03-24 07:24 UTC, aymeric-giraudet requested changes
Thanks @jonasNobile ! 
I think I had left it as a `js` file cause importing `./+page.svelte` was throwing TS errors and I was too tired to deal with it at that time but it's good if it works now 😅

Apart from `yarn.lock` it's all good for me !

2023-03-24 07:24 UTC, aymeric-giraudet commented on yarn.lock
I think it's best to leave it the way it was with `yarn`'s registry.
Perhaps you force using `npm`'s registry in your config files ?

2023-03-30 11:42 UTC, jonasNobile commented on yarn.lock
Interesting, this was definitely not my intention. I've reverted `yarn.lock` change.

2023-04-03 08:44 UTC, aymeric-giraudet approved these changes

2023-04-03 08:44 UTC, merged